parameters:
- name: typeWriterArtifactName
  type: string

- name: optionalPostCheckoutStep
  type: stepList
  default: # TODO is there a way to skip this without a dummy default task?
  - pwsh: |
      Write-Host "No optional post-checkout step is provided, this is expected in majority of cases" -ForegroundColor Green
    displayName: Skip optional post-checkout step

steps:
- template: use-dotnet-sdk.yml

- checkout: self
  displayName: checkout generator
  fetchDepth: 1
  submodules: recursive
  persistCredentials: true

- ${{ parameters.optionalPostCheckoutStep }}

- task: DotNetCoreCLI@2
  displayName: 'Build Typewriter'
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/src/Typewriter/Typewriter.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/src/Typewriter/bin/$(BuildConfiguration)/net5.0'
    contents: '**/*'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: Copy Typewriter executable

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: ${{ parameters.typeWriterArtifactName }}
