parameters:
- name: typeWriterArtifactName
  type: string

steps:
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: ${{ parameters.typeWriterArtifactName }}
    downloadPath: '$(Build.SourcesDirectory)'
